package com.pointage.Entities;

// Generated 26 juil. 2015 16:55:18 by Hibernate Tools 4.3.1

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CertiPtgregularise generated by hbm2java
 */
@Entity
@Table(name = "CERTI_PTGREGULARISE", catalog = "BioStar")
public class CertiPtgregularise implements java.io.Serializable {

	private int idPtgregularise;
	private String ndatetime;
	private Integer validjrnee;
	private Clob remarque;
	private String heurSupp;
	private Integer heurSuppindex;
	private Integer primefonction;
	private Set<TbUser> tbUsers = new HashSet<TbUser>(0);

	public CertiPtgregularise() {
	}

	public CertiPtgregularise(int idPtgregularise) {
		this.idPtgregularise = idPtgregularise;
	}

	public CertiPtgregularise(int idPtgregularise, 
			String ndatetime, Integer validjrnee, Clob remarque,
			String heurSupp, Integer heurSuppindex, Integer primefonction,
			Set<TbUser> tbUsers) {
		this.idPtgregularise = idPtgregularise;
		this.ndatetime = ndatetime;
		this.validjrnee = validjrnee;
		this.remarque = remarque;
		this.heurSupp = heurSupp;
		this.heurSuppindex = heurSuppindex;
		this.primefonction = primefonction;
		this.tbUsers = tbUsers;
	}

	@Id
	@Column(name = "id_ptgregularise", unique = true, nullable = false)
	public int getIdPtgregularise() {
		return this.idPtgregularise;
	}

	public void setIdPtgregularise(int idPtgregularise) {
		this.idPtgregularise = idPtgregularise;
	}
	
	@Column(name = "ndatetime", length = 100)
	public String getNdatetime() {
		return this.ndatetime;
	}

	public void setNdatetime(String ndatetime) {
		this.ndatetime = ndatetime;
	}

	@Column(name = "validjrnee")
	public Integer getValidjrnee() {
		return this.validjrnee;
	}

	public void setValidjrnee(Integer validjrnee) {
		this.validjrnee = validjrnee;
	}

	@Column(name = "remarque")
	public Clob getRemarque() {
		return this.remarque;
	}

	public void setRemarque(Clob remarque) {
		this.remarque = remarque;
	}

	@Column(name = "heurSupp", length = 100)
	public String getHeurSupp() {
		return this.heurSupp;
	}

	public void setHeurSupp(String heurSupp) {
		this.heurSupp = heurSupp;
	}

	@Column(name = "heurSuppindex")
	public Integer getHeurSuppindex() {
		return this.heurSuppindex;
	}

	public void setHeurSuppindex(Integer heurSuppindex) {
		this.heurSuppindex = heurSuppindex;
	}

	@Column(name = "primefonction")
	public Integer getPrimefonction() {
		return this.primefonction;
	}

	public void setPrimefonction(Integer primefonction) {
		this.primefonction = primefonction;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "certiPtgregularise")
	public Set<TbUser> getTbUsers() {
		return this.tbUsers;
	}

	public void setTbUsers(Set<TbUser> tbUsers) {
		this.tbUsers = tbUsers;
	}

}
