package com.pointage.Entities;

// Generated 26 juil. 2015 16:55:18 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbEventLogId generated by hbm2java
 */
@Embeddable
public class TbEventLogId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long ndateTime;
	private int neventIdn;
	private int nreaderIdn;
	private int nuserId;

	public TbEventLogId() {
	}

	public TbEventLogId(int ndateTime, int neventIdn, int nreaderIdn,
			int nuserId) {
		this.ndateTime = ndateTime;
		this.neventIdn = neventIdn;
		this.nreaderIdn = nreaderIdn;
		this.nuserId = nuserId;
	}

	@Column(name = "nDateTime", nullable = false)
	public long getNdateTime() {
		return this.ndateTime;
	}

	public void setNdateTime(long ndateTime) {
		this.ndateTime = ndateTime;
	}

	@Column(name = "nEventIdn", nullable = false)
	public int getNeventIdn() {
		return this.neventIdn;
	}

	public void setNeventIdn(int neventIdn) {
		this.neventIdn = neventIdn;
	}

	@Column(name = "nReaderIdn", nullable = false)
	public int getNreaderIdn() {
		return this.nreaderIdn;
	}

	public void setNreaderIdn(int nreaderIdn) {
		this.nreaderIdn = nreaderIdn;
	}

	@Column(name = "nUserID", nullable = false)
	public int getNuserId() {
		return this.nuserId;
	}

	public void setNuserId(int nuserId) {
		this.nuserId = nuserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbEventLogId))
			return false;
		TbEventLogId castOther = (TbEventLogId) other;

		return (this.getNdateTime() == castOther.getNdateTime())
				&& (this.getNeventIdn() == castOther.getNeventIdn())
				&& (this.getNreaderIdn() == castOther.getNreaderIdn())
				&& (this.getNuserId() == castOther.getNuserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNeventIdn();
		result = 37 * result + this.getNreaderIdn();
		result = 37 * result + this.getNuserId();
		return result;
	}

}
