package com.pointage.Entities;

// Generated 26 juil. 2015 16:55:18 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbEventLog generated by hbm2java
 */
@Entity
@Table(name = "TB_EVENT_LOG", catalog = "BioStar")
public class TbEventLog implements java.io.Serializable {

	private TbEventLogId id;
	private TbUser tbUser;
	private int neventLogIdn;
	private short nisLog;
	private short ntnaevent;
	private short nisUseTa;
	private short ntype;
	private String hours;

	public TbEventLog() {
	}

	public TbEventLog(TbEventLogId id, TbUser tbUser, int neventLogIdn,
			short nisLog, short ntnaevent, short nisUseTa, short ntype) {
		this.id = id;
		this.tbUser = tbUser;
		this.neventLogIdn = neventLogIdn;
		this.nisLog = nisLog;
		this.ntnaevent = ntnaevent;
		this.nisUseTa = nisUseTa;
		this.ntype = ntype;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ndateTime", column = @Column(name = "nDateTime", nullable = false)),
			@AttributeOverride(name = "neventIdn", column = @Column(name = "nEventIdn", nullable = false)),
			@AttributeOverride(name = "nreaderIdn", column = @Column(name = "nReaderIdn", nullable = false)),
			@AttributeOverride(name = "nuserId", column = @Column(name = "nUserID", nullable = false)) })
	public TbEventLogId getId() {
		return this.id;
	}

	public void setId(TbEventLogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nUserID", nullable = false, insertable = false, updatable = false)
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "nEventLogIdn", nullable = false)
	public int getNeventLogIdn() {
		return this.neventLogIdn;
	}

	public void setNeventLogIdn(int neventLogIdn) {
		this.neventLogIdn = neventLogIdn;
	}

	@Column(name = "nIsLog", nullable = false)
	public short getNisLog() {
		return this.nisLog;
	}

	public void setNisLog(short nisLog) {
		this.nisLog = nisLog;
	}

	@Column(name = "nTNAEvent", nullable = false)
	public short getNtnaevent() {
		return this.ntnaevent;
	}

	public void setNtnaevent(short ntnaevent) {
		this.ntnaevent = ntnaevent;
	}

	@Column(name = "nIsUseTA", nullable = false)
	public short getNisUseTa() {
		return this.nisUseTa;
	}

	public void setNisUseTa(short nisUseTa) {
		this.nisUseTa = nisUseTa;
	}

	@Column(name = "nType", nullable = false)
	public short getNtype() {
		return this.ntype;
	}

	public void setNtype(short ntype) {
		this.ntype = ntype;
	}

	public String getHours() {
		return hours;
	}

	public void setHours(String hours) {
		this.hours = hours;
	}

}
