package com.pointage.Entities;

// Generated 26 juil. 2015 16:55:18 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbTaResultId generated by hbm2java
 */
@Embeddable
public class TbTaResultId implements java.io.Serializable {

	private int ndateTime;
	private int nuserIdn;
	private int nshiftIdn;

	public TbTaResultId() {
	}

	public TbTaResultId(int ndateTime, int nuserIdn, int nshiftIdn) {
		this.ndateTime = ndateTime;
		this.nuserIdn = nuserIdn;
		this.nshiftIdn = nshiftIdn;
	}

	@Column(name = "nDateTime", nullable = false)
	public int getNdateTime() {
		return this.ndateTime;
	}

	public void setNdateTime(int ndateTime) {
		this.ndateTime = ndateTime;
	}

	@Column(name = "nUserIdn", nullable = false)
	public int getNuserIdn() {
		return this.nuserIdn;
	}

	public void setNuserIdn(int nuserIdn) {
		this.nuserIdn = nuserIdn;
	}

	@Column(name = "nShiftIdn", nullable = false)
	public int getNshiftIdn() {
		return this.nshiftIdn;
	}

	public void setNshiftIdn(int nshiftIdn) {
		this.nshiftIdn = nshiftIdn;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbTaResultId))
			return false;
		TbTaResultId castOther = (TbTaResultId) other;

		return (this.getNdateTime() == castOther.getNdateTime())
				&& (this.getNuserIdn() == castOther.getNuserIdn())
				&& (this.getNshiftIdn() == castOther.getNshiftIdn());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNdateTime();
		result = 37 * result + this.getNuserIdn();
		result = 37 * result + this.getNshiftIdn();
		return result;
	}

}
