package com.pointage.Entities;

// Generated 26 juil. 2015 16:55:18 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TbTaResult generated by hbm2java
 */
@Entity
@Table(name = "TB_TA_RESULT", catalog = "BioStar")
public class TbTaResult implements java.io.Serializable {

	private TbTaResultId id;
	private TbUser tbUser;
	private int ndailyScheduleIdn;
	private int nstartTime;
	private int nendTime;
	private String sstartEvent;
	private String sendEvent;
	private int ntaresult;
	private int nworkTime;
	private int nisModify;
	private int nlateInTime;
	private int nearlyOutTime;

	public TbTaResult() {
	}

	public TbTaResult(TbTaResultId id, TbUser tbUser, int ndailyScheduleIdn,
			int nstartTime, int nendTime, String sstartEvent, String sendEvent,
			int ntaresult, int nworkTime, int nisModify, int nlateInTime,
			int nearlyOutTime) {
		this.id = id;
		this.tbUser = tbUser;
		this.ndailyScheduleIdn = ndailyScheduleIdn;
		this.nstartTime = nstartTime;
		this.nendTime = nendTime;
		this.sstartEvent = sstartEvent;
		this.sendEvent = sendEvent;
		this.ntaresult = ntaresult;
		this.nworkTime = nworkTime;
		this.nisModify = nisModify;
		this.nlateInTime = nlateInTime;
		this.nearlyOutTime = nearlyOutTime;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ndateTime", column = @Column(name = "nDateTime", nullable = false)),
			@AttributeOverride(name = "nuserIdn", column = @Column(name = "nUserIdn", nullable = false)),
			@AttributeOverride(name = "nshiftIdn", column = @Column(name = "nShiftIdn", nullable = false)) })
	public TbTaResultId getId() {
		return this.id;
	}

	public void setId(TbTaResultId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nUserIdn", nullable = false, insertable = false, updatable = false)
	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	@Column(name = "nDailyScheduleIdn", nullable = false)
	public int getNdailyScheduleIdn() {
		return this.ndailyScheduleIdn;
	}

	public void setNdailyScheduleIdn(int ndailyScheduleIdn) {
		this.ndailyScheduleIdn = ndailyScheduleIdn;
	}

	@Column(name = "nStartTime", nullable = false)
	public int getNstartTime() {
		return this.nstartTime;
	}

	public void setNstartTime(int nstartTime) {
		this.nstartTime = nstartTime;
	}

	@Column(name = "nEndTime", nullable = false)
	public int getNendTime() {
		return this.nendTime;
	}

	public void setNendTime(int nendTime) {
		this.nendTime = nendTime;
	}

	@Column(name = "sStartEvent", nullable = false, length = 32)
	public String getSstartEvent() {
		return this.sstartEvent;
	}

	public void setSstartEvent(String sstartEvent) {
		this.sstartEvent = sstartEvent;
	}

	@Column(name = "sEndEvent", nullable = false, length = 32)
	public String getSendEvent() {
		return this.sendEvent;
	}

	public void setSendEvent(String sendEvent) {
		this.sendEvent = sendEvent;
	}

	@Column(name = "nTAResult", nullable = false)
	public int getNtaresult() {
		return this.ntaresult;
	}

	public void setNtaresult(int ntaresult) {
		this.ntaresult = ntaresult;
	}

	@Column(name = "nWorkTime", nullable = false)
	public int getNworkTime() {
		return this.nworkTime;
	}

	public void setNworkTime(int nworkTime) {
		this.nworkTime = nworkTime;
	}

	@Column(name = "nIsModify", nullable = false)
	public int getNisModify() {
		return this.nisModify;
	}

	public void setNisModify(int nisModify) {
		this.nisModify = nisModify;
	}

	@Column(name = "nLateInTime", nullable = false)
	public int getNlateInTime() {
		return this.nlateInTime;
	}

	public void setNlateInTime(int nlateInTime) {
		this.nlateInTime = nlateInTime;
	}

	@Column(name = "nEarlyOutTime", nullable = false)
	public int getNearlyOutTime() {
		return this.nearlyOutTime;
	}

	public void setNearlyOutTime(int nearlyOutTime) {
		this.nearlyOutTime = nearlyOutTime;
	}

}
