package com.pointage.Entities;

// Generated 23 juil. 2015 09:18:12 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", catalog = "BioStar")
public class Users implements java.io.Serializable {

	private int userId;
	private String userName;
	private String password;
	private boolean actived;	

	public Users() {
	}

	public Users(String userName, String password) {
		super();
		this.userName = userName;
		this.password = password;
	}

	public Users(int userId) {
		this.userId = userId;
	}

	public Users(int userId, String userName, String password, Boolean actived) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.actived = actived;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "userName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "actived")
	public Boolean getActived() {
		return this.actived;
	}

	public void setActived(Boolean actived) {
		this.actived = actived;
	}

}
